project:
  type: website

website:
  title: "Fieldnotes"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Feministische Filmgeschichte"
        file: feministische-filmgeschichte.qmd
      - text: "Sammlungen"
        file: archives.qmd
      - text: "Tätigkeiten"
        file: taetigkeiten.qmd        
      - text: "Dokumentation Wikidata"
        file: requesting-wikidata.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


